user_list:
  controller: WebSite\Controller\UserController:listUsersAction

user_show:
  controller: WebSite\Controller\UserController:showUserAction

user_add:
  controller: WebSite\Controller\UserController:addUserAction

user_delete:
  controller: WebSite\Controller\UserController:deleteUserAction

user_log:
  controller: WebSite\Controller\UserController:logUserAction

user_logOut:
  controller: WebSite\Controller\UserController:logOutAction

home:
  controller: WebSite\Controller\HomeController:showHomeAction

product_list:
  controller: WebSite\Controller\ProductController:listProductsAction

product_show:
  controller: WebSite\Controller\ProductController:showProductAction

product_add:
  controller: WebSite\Controller\ProductController:addProductAction

product_delete:
  controller: WebSite\Controller\ProductController:deleteProductAction
